title:(https://github.com/DigitalVigilantesofficial/BAT404.github.io/blob/main/assets/images/icons8-batman-48.png) BATMAN404's Websit
theme: jekyll-theme-hacker
kramdown:
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
